# 存储表结构字符串
STOCK_BUSINESS_SCHEMA = """
CREATE TABLE `stock_business` (
  `ts_code` varchar(20) NOT NULL COMMENT 'TS股票代码',
  `stock_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '股票名称',
  `trade_date` date NOT NULL COMMENT '交易日期',
  `daily_close` decimal(10,2) DEFAULT NULL COMMENT '当日收盘价',
  `turnover_rate` decimal(10,2) DEFAULT NULL COMMENT '换手率（%）',
  `turnover_rate_f` decimal(10,2) DEFAULT NULL COMMENT '换手率（自由流通股）',
  `volume_ratio` decimal(10,2) DEFAULT NULL COMMENT '量比',
  `pe` decimal(10,2) DEFAULT NULL COMMENT '市盈率（总市值/净利润， 亏损的PE为空）',
  `pe_ttm` decimal(10,2) DEFAULT NULL COMMENT '市盈率（TTM，亏损的PE为空）',
  `pb` decimal(10,2) DEFAULT NULL COMMENT '市净率（总市值/净资产）',
  `ps` decimal(10,2) DEFAULT NULL COMMENT '市销率',
  `ps_ttm` decimal(10,2) DEFAULT NULL COMMENT '市销率（TTM）',
  `dv_ratio` decimal(10,2) DEFAULT NULL COMMENT '股息率 （%）',
  `dv_ttm` decimal(10,2) DEFAULT NULL COMMENT '股息率（TTM）（%）',
  `total_share` decimal(20,2) DEFAULT NULL COMMENT '总股本 （万股）',
  `float_share` decimal(20,2) DEFAULT NULL COMMENT '流通股本 （万股）',
  `free_share` decimal(20,2) DEFAULT NULL COMMENT '自由流通股本 （万）',
  `total_mv` decimal(20,2) DEFAULT NULL COMMENT '总市值 （万元）',
  `circ_mv` decimal(20,2) DEFAULT NULL COMMENT '流通市值（万元）',
  `factor_open` decimal(10,2) DEFAULT NULL COMMENT '开盘价',
  `factor_high` decimal(10,2) DEFAULT NULL COMMENT '最高价',
  `factor_low` decimal(10,2) DEFAULT NULL COMMENT '最低价',
  `factor_pre_close` decimal(10,2) DEFAULT NULL COMMENT '昨收价',
  `factor_change` decimal(10,2) DEFAULT NULL COMMENT '涨跌额',
  `factor_pct_change` decimal(10,2) DEFAULT NULL COMMENT '涨跌幅',
  `factor_vol` decimal(20,2) DEFAULT NULL COMMENT '成交量',
  `factor_amount` decimal(20,2) DEFAULT NULL COMMENT '成交额',
  `factor_adj_factor` decimal(10,2) DEFAULT NULL COMMENT '复权因子',
  `factor_open_hfq` decimal(10,2) DEFAULT NULL COMMENT '后复权开盘价',
  `factor_open_qfq` decimal(10,2) DEFAULT NULL COMMENT '前复权开盘价',
  `factor_close_hfq` decimal(10,2) DEFAULT NULL COMMENT '后复权收盘价',
  `factor_close_qfq` decimal(10,2) DEFAULT NULL COMMENT '前复权收盘价',
  `factor_high_hfq` decimal(10,2) DEFAULT NULL COMMENT '后复权最高价',
  `factor_high_qfq` decimal(10,2) DEFAULT NULL COMMENT '前复权最高价',
  `factor_low_hfq` decimal(10,2) DEFAULT NULL COMMENT '后复权最低价',
  `factor_low_qfq` decimal(10,2) DEFAULT NULL COMMENT '前复权最低价',
  `factor_pre_close_hfq` decimal(10,2) DEFAULT NULL COMMENT '后复权昨收价',
  `factor_pre_close_qfq` decimal(10,2) DEFAULT NULL COMMENT '前复权昨收价',
  `factor_macd_dif` decimal(10,2) DEFAULT NULL COMMENT 'MACD DIF值',
  `factor_macd_dea` decimal(10,2) DEFAULT NULL COMMENT 'MACD DEA值',
  `factor_macd` decimal(10,2) DEFAULT NULL COMMENT 'MACD值',
  `factor_kdj_k` decimal(10,2) DEFAULT NULL COMMENT 'KDJ K值',
  `factor_kdj_d` decimal(10,2) DEFAULT NULL COMMENT 'KDJ D值',
  `factor_kdj_j` decimal(10,2) DEFAULT NULL COMMENT 'KDJ J值',
  `factor_rsi_6` decimal(10,2) DEFAULT NULL COMMENT 'RSI 6日',
  `factor_rsi_12` decimal(10,2) DEFAULT NULL COMMENT 'RSI 12日',
  `factor_rsi_24` decimal(10,2) DEFAULT NULL COMMENT 'RSI 24日',
  `factor_boll_upper` decimal(10,2) DEFAULT NULL COMMENT '布林上轨',
  `factor_boll_mid` decimal(10,2) DEFAULT NULL COMMENT '布林中轨',
  `factor_boll_lower` decimal(10,2) DEFAULT NULL COMMENT '布林下轨',
  `factor_cci` decimal(10,2) DEFAULT NULL COMMENT 'CCI指标',
  `moneyflow_pct_change` decimal(10,2) DEFAULT NULL COMMENT '涨跌幅',
  `moneyflow_latest` decimal(10,2) DEFAULT NULL COMMENT '最新价',
  `moneyflow_net_amount` decimal(20,2) DEFAULT NULL COMMENT '净流入额',
  `moneyflow_net_d5_amount` decimal(20,2) DEFAULT NULL COMMENT '5日净流入额',
  `moneyflow_buy_lg_amount` decimal(20,2) DEFAULT NULL COMMENT '大单买入额',
  `moneyflow_buy_lg_amount_rate` decimal(10,2) DEFAULT NULL COMMENT '大单买入额占比',
  `moneyflow_buy_md_amount` decimal(20,2) DEFAULT NULL COMMENT '中单买入额',
  `moneyflow_buy_md_amount_rate` decimal(10,2) DEFAULT NULL COMMENT '中单买入额占比',
  `moneyflow_buy_sm_amount` decimal(20,2) DEFAULT NULL COMMENT '小单买入额',
  `moneyflow_buy_sm_amount_rate` decimal(10,2) DEFAULT NULL COMMENT '小单买入额占比',
  `ma5` decimal(10,3) DEFAULT NULL COMMENT '5日均线',
  `ma10` decimal(10,3) DEFAULT NULL COMMENT '10日均线',
  `ma20` decimal(10,3) DEFAULT NULL COMMENT '20日均线',
  `ma30` decimal(10,3) DEFAULT NULL COMMENT '30日均线',
  `ma60` decimal(10,3) DEFAULT NULL COMMENT '60日均线',
  `ma120` decimal(10,3) DEFAULT NULL COMMENT '120日均线'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='股票业务表';
""" 